### ISSUE TITLE
Enrollment request

### ISSUE THREAD

**Issue by ibny** [CSC-285-Fall-2017/How-To-Enroll#13]
First Name: Irving
Last Name: Bruckstein
Hofstra Email: IBRUCK1@pride.Hofstra.edu

**Comment by accmpp** [comment]
Thanks Irving,

You have been Invited! Go to https://github.com/CSC-285-Fall-2017 to accept the invitation.

Prof. Pappalardo

**Comment by accmpp** [comment]
Hi Irv, 

It looks like you still need to accept the invite to join our CSC-285 class organization.  
Please go to https://github.com/CSC-285-Fall-2017 to accept the invitation.

Best,
Prof. Pappalardo

**Comment by ibny** [comment]
Prof. Pappalardo:
Thanks for the follow up.  I muddling through this as my very first time using github... I thought I had joined but did get errors on prior attempts to access the link.  I took screenshots of my prior attempts to upload lab 1.  It looked like it was there, but following your links this time, it seems I have now fully joined.  Can you please confirm from you line of sight?
See my attached screen shot from prior uploads of my lab, prior to accepting this invite.  
Will you consider my prior request to give me a grade based on the merits of my submission this time around.  I can also forward emails between myself and Dean Liang detailing my delayed start to getting connected with the class portal if that would help.
Thanks again...Irv
 

    On Sunday, September 17, 2017 1:21 AM, Markey Pappalardo <notifications@github.com> wrote:
 

 Hi Irv,It looks like you still need to accept the invite to join our CSC-285 class organization.
Please go to https://github.com/CSC-285-Fall-2017 to accept the invitation.Best,
Prof. Pappalardo—

**Comment by accmpp** [comment]
Congratulations Irv! 

You have successfully joined the CSC-285 Class Repository! :smile:  I'm glad you were able to figure it out! I guess that explains why you never responded to any of my previous emails. All Blackboard class correspondense always uses your Hofstra Gmail (ibruck1@pride.hofstra.edu) only. Now you can go to https://github.com/CSC-285-Fall-2017 to see your repositories and look around. 

Note, I also sent you an email last night that I received your Lab 1 successfully, tested it and re-adjusted your grade. Please check Blackboard/MyGrades link.

Best,
Prof. Pappalardo
