### ISSUE TITLE
Enrollment request

### ISSUE THREAD

**Issue by mrK01** [CSC-285-Fall-2017/How-To-Enroll#7]
First Name: Camilo
Last Name: Chaves
Hofstra Email: cchave6@pride.hofstra.edu

**Comment by accmpp** [comment]
Thanks Camilo,

You have been Invited! Go to https://github.com/CSC-285-Fall-2017 to accept the invitation.

Prof. Pappalardo

**Comment by mrK01** [comment]
Hello Proffesor Pappalardo,

I'm looking forward to learn from you this semester. I submitted my "Lab1"
wrong the first time but the second submission is fine to the best of my
knowledge.
I apologize for the inconvenience and it won't happen again, I'm just new
to Mobile Device Programming, GitHub, the Android Studio, etc. so I was a
bit overwhelmed initially. Thanks for your instructions, they were very
helpful!

Regards,
Camilo

On Fri, Sep 8, 2017 at 12:18 PM, Markey Pappalardo <notifications@github.com
